### ISSUE TITLE
Cannot generate paraphrases of questions

### ISSUE THREAD

**Issue by noagarcia** [zaynmi/seada-vqa#3]
Hi!

Thank you for your work and for releasing the code of this interesting paper. 

I am at trying to generate paraphrases of the questions (step 1) but the code fails at some point.

This is the command I run:

`python main.py --attack_only --attack_mode q --attack_al sea --fliprate 0 --topk 1 --paraphrase_data train --attacked_checkpoint data/bs256.pth`

And I get the following output:

```
--------------------------------------------------
Namespace(adv_delay=10, adv_end=15, advloss_w=1, advtrain=False, advtrain_data='train', alpha=0.5, attack_al='sea', attack_mode='q', attack_only=True, attacked_checkpoint='data/bs256.pth', checkpoint=None, describe='describe your setting', epsilon=0.3, eval_advtrain=False, fliprate=0.0, generate_adv_example=True, iteration=2, lr_decay=15, name=[], paraphrase_data='train', resume=None, samples_frac=1, test_advtrain=False, topk=1, vqacp=False)
--------------------------------------------------
Num obj:  100
Num epochs:  23
Batch size:  256
Model type:  baseline
Optimization Method:  Adamax
Schedule Method:  warm_up
Loss Method:  binary_cross_entropy_with_logits
Clip Value:  0.25
Init LR:  0.001
LR decay step:  2
LR decay rate:  0.25
LR half life:  50000
Normalize visual feature:  False
Print Gradient:  False
Normalize Box Size:  False
Max answer choice:  3129
Manually set max question lenght:  666
Random Seed:  5225
gradual_warmup_steps:  [0.0005, 0.001, 0.0015, 0.002]
Weight Decay:  0.0
--------------------------------------------------
GPU ID 0
Loading model parameters.
Loading model parameters.
Loading model parameters.
Loading model parameters.
sea :   0% 0/1699 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 74, in <module>
    main()
  File "main.py", line 60, in main
    attackvqa.attack(attackvqa.val_loader)
  File "/home/noa/Projects/seada-vqa/seada/adversarial_vqa.py", line 178, in attack
    v, b, v_mask, q_adv, q_len_adv, q_mask_adv, answer, q_str_adv, image_id_adv, q_id_adv = self.adversarial.perturb((v, b, q, q_str, v_mask, q_mask, image_id, q_id, q_len), y=answer, oripred=clean_logits)
  File "/home/noa/Projects/seada-vqa/seada/attacks.py", line 193, in perturb
    q_adv, q_len_adv, q_mask_adv, q_str_adv, flipsign = self.find_flips(q_str[i], visual=(v[i], b[i], v_mask[i]), topk=topk, fliprate=fliprate, threshold=-10, oripred=oripred[i])
  File "/home/noa/Projects/seada-vqa/seada/attacks.py", line 233, in find_flips
    paraphrases = self.ps.generate_paraphrases(instance_for_onmt, topk=topk+1, edit_distance_cutoff=4, threshold=threshold)
  File "/home/noa/Projects/seada-vqa/seada/sea/paraphrase_scorer.py", line 797, in generate_paraphrases
    translation, mapping = choose_forward_translation(sentence, to, back, n=5)
  File "/home/noa/Projects/seada-vqa/seada/sea/paraphrase_scorer.py", line 31, in choose_forward_translation
    return_from_mapping=True)[0]
  File "/home/noa/Projects/seada-vqa/seada/sea/onmt_model.py", line 182, in translate
    self.translator.translate(batch, data))
  File "/home/noa/anaconda2/envs/seada/lib/python3.6/site-packages/OpenNMT_py-0.1-py3.6.egg/onmt/Translator.py", line 235, in translate
  File "/home/noa/anaconda2/envs/seada/lib/python3.6/site-packages/OpenNMT_py-0.1-py3.6.egg/onmt/Translator.py", line 235, in <listcomp>
  File "/home/noa/anaconda2/envs/seada/lib/python3.6/site-packages/OpenNMT_py-0.1-py3.6.egg/onmt/Translator.py", line 63, in buildTargetTokens
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number
sea :   0% 0/1699 [01:08<?, ?it/s]

```
Do you have any clue how can I solve it and run the code to generate the questions with paraphrases?

Thanks

Noa

**Comment by jasscia18** [comment]
Did you download the translation models?  I can't download it now.  Can you share it with me?

**Comment by zaynmi** [comment]
@noagarcia Hi Noa, I could run with the command `python main.py --attack_only --attack_mode q --attack_al sea --fliprate 0 --topk 1 --paraphrase_data train --attacked_checkpoint data/bs256.pth` on my machine. What is the version of your python, pytorch, and cudatoolkit?

**Comment by zaynmi** [comment]
@jasscia18 Hi, is this [link](https://drive.google.com/open?id=1b2upZvq5kM0lN0T7YaAY30xRdbamuk9y) invalid? I could download it on my side.

**Comment by jasscia18** [comment]
> @jasscia18 Hi, is this [link](https://drive.google.com/open?id=1b2upZvq5kM0lN0T7YaAY30xRdbamuk9y) invalid? I could download it on my side.

Thanks very much.

**Comment by noagarcia** [comment]
@zaynmi 

The version of my packages (I installed everything from scratch just in case but the error persists):
- `cudatoolkit               10.0.130`
- `python                    3.6.12`
- `pytorch                   1.0.1`


According to the output error, it seems it has to do with OpenNMT or the Translator model?

**Comment by zaynmi** [comment]
@noagarcia Sorry, I had pushed a wrong version of OpenNMT repo. The correct OpenNMT repo is updated just now, please use following command to re-install the OpenNMT package.
```
git clone https://github.com/zaynmi/OpenNMT-py.git
cd OpenNMT-py
python setup.py install
cd ..
```

**Comment by noagarcia** [comment]
Thank you, is working now!
